"""Add title and page_size to Config model

Revision ID: 930e876c9a5f
Revises: add_title_to_pdstables
Create Date: 2025-05-01 18:15:53.407953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '930e876c9a5f'
down_revision: Union[str, None] = 'add_title_to_pdstables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PDSTABLES', sa.Column('page_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PDSTABLES', 'page_size')
    # ### end Alembic commands ###
