"""Add sync history table

Revision ID: a2a1ae1a3ac1
Revises: 
Create Date: 2025-04-24 21:40:25.613397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a1ae1a3ac1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYNCHISTORY',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pds_table_id', sa.UUID(), nullable=False),
    sa.Column('sync_guid', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_columns', sa.Integer(), nullable=False),
    sa.Column('total_updates', sa.Integer(), nullable=True),
    sa.Column('total_creates', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['pds_table_id'], ['PDSTABLES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SYNCHISTORY')
    # ### end Alembic commands ###
